INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('COMBINGMILL', 'ORGANIZATION', '1970-01-01');
INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('SPINNINGMILL', 'ORGANIZATION', '1970-01-01');
INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('ADMIN', 'ORGANIZATION', '1970-01-01');

INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('CM-TR010', 'TRACE', '1970-01-01');
INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('CM-TR020', 'TRACE', '1970-01-01');
INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('SM-TR010', 'TRACE', '1970-01-01');
INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('SM-TR020', 'TRACE', '1970-01-01');

INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('ADMIN', 'USER', '1970-01-01');
INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('USER', 'USER', '1970-01-01');
INSERT INTO KIND(NAME, "TABLE", CREATED_DATE) VALUES ('DISABLED', 'USER', '1970-01-01');

INSERT INTO ORGANISATION(NAME, COUNTRY, KIND_ID, CREATED_DATE)
SELECT NAME, 'FR', ID, '1970-01-01'
FROM KIND
WHERE "TABLE" = 'ORGANIZATION';


INSERT INTO USER(CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, KIND_ID, ORGANISATION_ID)
VALUES('1970-01-01', 'user@comb.com', 'User', 'COMB', '$2a$10$CGe6isnRnCEaDczyYoHxsesIeivo/KJIluvHROSU49CP1bXvC30Im', SELECT ID FROM KIND WHERE NAME = 'USER', SELECT ID FROM ORGANISATION WHERE NAME = 'COMBINGMILL');
INSERT INTO USER(CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, KIND_ID, ORGANISATION_ID)
VALUES('1970-01-01', 'user@spin1.com', 'User', 'SPIN', '$2a$10$CGe6isnRnCEaDczyYoHxsesIeivo/KJIluvHROSU49CP1bXvC30Im', SELECT ID FROM KIND WHERE NAME = 'USER', SELECT ID FROM ORGANISATION WHERE NAME = 'SPINNINGMILL');
INSERT INTO USER(CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, KIND_ID, ORGANISATION_ID)
VALUES('1970-01-01', 'admin@admin.com', 'Admin', 'ADMIN', '$2a$10$CGe6isnRnCEaDczyYoHxsesIeivo/KJIluvHROSU49CP1bXvC30Im', SELECT ID FROM KIND WHERE NAME = 'USER', SELECT ID FROM ORGANISATION WHERE NAME = 'ADMIN');

INSERT INTO TRACE(CREATED_DATE,ORGANISATION_NAME,WOOL_TOP_GROSS_WEIGHT,WOOL_TOP_LOT_NUMBER,WOOL_TOP_NET_WEIGHT,KIND_ID, ORGANISATION_ID, USER_ID)
VALUES('1970-01-01', 'Combing Mill', 1020, 'WTL_01',1010, SELECT ID FROM KIND WHERE NAME = 'COMBINGMILL', SELECT ID FROM ORGANISATION WHERE NAME = 'COMBINGMILL', SELECT ID FROM USER WHERE EMAIL = 'user@comb.com');
INSERT INTO TRACE(CREATED_DATE,ORGANISATION_NAME,WOOL_TOP_GROSS_WEIGHT,WOOL_TOP_LOT_NUMBER,WOOL_TOP_NET_WEIGHT,KIND_ID, ORGANISATION_ID, USER_ID)
VALUES('1970-01-01', 'Combing Mill', 1010, 'WTL_01',1000, SELECT ID FROM KIND WHERE NAME = 'COMBINGMILL', SELECT ID FROM ORGANISATION WHERE NAME = 'COMBINGMILL', SELECT ID FROM USER WHERE EMAIL = 'admin@admin.com');

INSERT INTO TRACE(CREATED_DATE,ORGANISATION_NAME,WOOL_TOP_GROSS_WEIGHT,WOOL_TOP_LOT_NUMBER,WOOL_TOP_NET_WEIGHT,KIND_ID, ORGANISATION_ID, USER_ID)
VALUES('1970-01-01', 'Spinning Mill', 505, 'WTL_01',500, SELECT ID FROM KIND WHERE NAME = 'SPINNINGMILL', SELECT ID FROM ORGANISATION WHERE NAME = 'SPINNINGMILL', SELECT ID FROM USER WHERE EMAIL = 'admin@admin.com');
INSERT INTO TRACE(CREATED_DATE,ORGANISATION_NAME,WOOL_TOP_GROSS_WEIGHT,WOOL_TOP_LOT_NUMBER,WOOL_TOP_NET_WEIGHT,KIND_ID, ORGANISATION_ID, USER_ID)
VALUES('1970-01-01', 'Spinning Mill', 505, 'WTL_01',500, SELECT ID FROM KIND WHERE NAME = 'SPINNINGMILL', SELECT ID FROM ORGANISATION WHERE NAME = 'SPINNINGMILL', SELECT ID FROM USER WHERE EMAIL = 'user@spin1.com');
INSERT INTO TRACE(CREATED_DATE,ORGANISATION_NAME,WOOL_TOP_GROSS_WEIGHT,WOOL_TOP_LOT_NUMBER,WOOL_TOP_NET_WEIGHT,KIND_ID, ORGANISATION_ID, USER_ID)
VALUES('1970-01-01', 'Spinning Mill', 1010, 'WTL_01',1000, SELECT ID FROM KIND WHERE NAME = 'SPINNINGMILL', SELECT ID FROM ORGANISATION WHERE NAME = 'SPINNINGMILL', SELECT ID FROM USER WHERE EMAIL = 'user@spin1.com');



